version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: cafe-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cafe_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: cafe-redis
    restart: always
    ports:
      - "6379:6379"

  api:
    build: .
    container_name: cafe-api
    restart: always
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/cafe_db?schema=public
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=docker_secret_access_key_98765
      - JWT_REFRESH_SECRET=docker_secret_refresh_key_56789
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data:
